/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId */

#ifndef _Included_io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId
#define _Included_io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId
	 * Method:    get
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId_get
	(JNIEnv*, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
